### ISSUE TITLE
Trouble getting started

### ISSUE THREAD

**Issue by kofalt** [talons/talons#26]
Apologies in advance if this is bone-headed, but I can't get the external authenticator to work.
A simple example:

``` python
from talons.auth import middleware
from talons.auth import basicauth, httpheader, htpasswd, external

def authme(identity):
    return identity.login == identity.key

config = dict(
    httpheader_user     = 'test',
    httpheader_key      = 'test',
    external_authfn     = authme,
    external_sets_roles = True,
)

auth_middleware = middleware.create_middleware(
    identify_with     = [ basicauth.Identifier, httpheader.Identifier ],
    authenticate_with = external.Authenticator,
    **config
)

app = falcon.API(before=[auth_middleware])
```

Result:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 144, in run
    self.load()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 356, in import_app
    __import__(module)
  File "server/app.py", line 25, in <module>
    **config
  File "/usr/local/lib/python2.7/dist-packages/talons/auth/middleware.py", line 130, in create_middleware
    authenticate_with[x] = a = a(**conf)
  File "/usr/local/lib/python2.7/dist-packages/talons/auth/external.py", line 59, in __init__
    self.authfn = helpers.import_function(authfn)
  File "/usr/local/lib/python2.7/dist-packages/talons/helpers.py", line 33, in import_function
    mod_str, _sep, class_str = import_str.rpartition('.')
AttributeError: 'function' object has no attribute 'rpartition'
```

Any guidance appreciated. Thanks!

**Comment by max-barry** [comment]
Authme is a function. You need to supply a dot notation path to the function, not a raw function.

For example, stick authme in a file called b, in a folder called c with an __init__.py in both. Folder structure will be:
c
  -  __init__.py
  -  b.py (contains authme function)

Now supply the following in your conf:

external_authfn = "c.b.authme"

Should work that way.

**Comment by kofalt** [comment]
@max-barry This turned out to be multiple problems that were resolved in IRC, among them that the published version of talons was not up-to-date with Github :)

@jaypipes and I worked it out in [this gist](https://gist.github.com/kofalt/ddfc0d4052f2d45e9eee) for anyone needing an example.
Among other things, note the different key names in the `config` dict.
